version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Build completed on `date`
      - cd JavaWeb-master
      - mvn clean package -Dmaven.test.skip
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - AshuwebApplication/target/*.jar
  discard-paths: yes